### PR TITLE
Use snake_case instead of CamelCase

### PR DESCRIPTION
**Pull request by Nyholm**
Ping @thomasglachant

### CODE REVIEW

**Comment by thomasglachant** [comment]
Ok for me, much pretty !

**Comment by thomasglachant** [comment]
@Nyholm Do you know when the next php-cache adapter version will be tagged ?

**Comment by Nyholm** [comment]
In 5 min. Just after I merge this

**Comment by Nyholm** [comment]
I just tagged 0.3.4

**Comment by thomasglachant** [comment]
Is it planned to tag the "cache/chain-adapter" ?

**Comment by Nyholm** [comment]
I will make sure to put down some work after SymfonyCat. We should also have a discussion about tagging 1.0 for our adapters

**Comment by thomasglachant** [comment]
Great news ! I'm very interested by the project. Keep me informed.

**Pull request merged**
